enableGlobalCache: true

packageExtensions:
  example@*:
    dependencies:
      '@rollup/pluginutils': ^4.1.0
      change-case: ^4.1.2
      debug: ^4.3.2
      es-module-lexer: ^0.6.0
      magic-string: ^0.25.7

pnpMode: loose

yarnPath: .yarn/releases/yarn-berry.cjs
